### ISSUE TITLE
Feedback Requested by Adam

### ISSUE THREAD

**Issue by loganevasco** [universe/vapid#23]
Website Domain Feedback for Adam

 1. [x] Note: Love the cute “This one’s on us!” section
 2. [ ] Suggestion: Second line on “This one’s on us” section
 3. [ ]  Suggestion: Header and Helper Text at the top
 4. [ ] Suggestion: Add additional helper text
 5. [ ] Weirdness:
 6. [x] Weirdness/Bug?:Button Errors
 7. [ ] Bug: When adding new domain name, 2nd CNAME is clicked automatically?
 8. [ ] Suggestion: Documentation

This is awesome Adam, great job! So excited for this!

Just a few things-

**1. Note: Love the cute “This one’s on us!” section**
<img width="640" alt="Screen Shot 2023-05-30 at 6 17 14 PM" src="https://github.com/universe/vapid/assets/65923862/1900d28a-3d26-48a7-8f71-36e14900da39">

**2. Suggestion: Second line on “This one’s on us” section**
Maybe change the second line copy to, “This complimentary domain is ready to go when you are.” 

**3. Suggestion: Header and Helper Text at the top**
Would be nice to have a Header above the “Domain Name” field and button because they get kinda lost. Maybe just “Add Domain Names” then some helper text below like “Add domain names that you’ve purchased from a domain registrar here. Don’t have a custom domain name yet? Check out [Google Domains](https://domains.google.com/registrar/search) or [NameCheap](https://www.namecheap.com/).”
<img width="652" alt="Screen Shot 2023-05-30 at 6 01 54 PM" src="https://github.com/universe/vapid/assets/65923862/dedde2a8-a798-49d8-9c80-85441b610568">

**4. Suggestion: Add additional helper text**
It took me a minute to figure out why there were so many CNAME things. I don’t think I’d seen that before. What if we added another helper text above the DNS Record 48 hours thing that says, “Tip: Go to your domain registrar and add each of the above CNAMEs to your DNS Records.”

**5. Weirdness:** 
I tried adding a junk domain I have, “trashdogproductions.com”
I can’t get the top CNAME to resolve. 
<img width="637" alt="Screen Shot 2023-05-30 at 6 19 31 PM" src="https://github.com/universe/vapid/assets/65923862/ce846ce4-5ffe-48fc-b7ce-e5da1b659096">

**6. Weirdness/Bug?:** Button Errors
Also when I hit “Retry,” the “Add Domain Name” button changes to says“user.isAdminUserRole is not a function” or if I clear that it says “Invalid Domain.” It's a little confusing that the error state is showing up there instead of in the "trashdogproductions.com" box.
<img width="660" alt="Screen Shot 2023-05-30 at 6 13 29 PM" src="https://github.com/universe/vapid/assets/65923862/bd9ba716-1884-413f-90e2-4524a94b469d">
<img width="646" alt="Screen Shot 2023-05-30 at 6 13 51 PM" src="https://github.com/universe/vapid/assets/65923862/0dc500c9-9e44-4e5d-8eca-a5276e90f592">

**7. Bug: When adding new domain name, 2nd CNAME is clicked automatically?**
When I added this fake one, "mycampaign.com" it shows the second domain name clicked. Same thing happened with trashdogproductions.com. This eventually goes way if you hit refresh. 
<img width="641" alt="Screen Shot 2023-05-30 at 5 50 49 PM" src="https://github.com/universe/vapid/assets/65923862/3d3a748b-e346-4faf-bd65-ae4d70c67673">

**8. Suggestion: Documentation**
We should make a page on notion or docs.universe.app to explain how to do this. Then we could link to that page directly in the helper text.

FYI this is what my registrar's Cname added looks like, kinda nice- 
<img width="945" alt="Screen Shot 2023-05-30 at 5 49 12 PM" src="https://github.com/universe/vapid/assets/65923862/4a663995-5f23-403e-a275-76c97aa942d4">

**Comment by loganevasco** [comment]
PS: I didn't try making a different domain the "Primary." Was kind scared it might be a problem.

**Comment by amiller-gh** [comment]
This belongs in aether!
