### ISSUE TITLE
BUG: When logging in it asks you to choose a subdomain name again

### ISSUE THREAD

**Issue by loganevasco** [universe/vapid#37]
When I login at website.univerese.app it always bring up the "Select Your Personal Sub-domain name" page (see screenshot below). You have to hit "cancel" to get to the editor. 

This recently confused a new website builder client, Jana, and it also is bothersome for me even. It would be nice to just go to the builder if you've previously set up your account. 

<img width="1363" alt="Screenshot 2024-03-19 at 10 39 25 AM" src="https://github.com/universe/vapid/assets/65923862/ddfc3059-bbc6-485b-8a2f-f2c1e1a315ee">

**Comment by amiller-gh** [comment]
fixed IIRC
