### ISSUE TITLE
Bug: iPhone mobile page viewing issue 

### ISSUE THREAD

**Issue by loganevasco** [universe/vapid#40]
**Describe the bug**
When viewing some pages on iphones (in any browser) the footer of the website is displaying too high up and obscuring the text. See screenshots below. 

**To Reproduce**
1. On iphone open chrome or safari and go to flaviorbravo.com
2. Go to the "About Flavio" page from the menu
3. Scroll down

Can reproduce on Nik's phone

**Screenshots**
![IMG-20240627-WA0000](https://github.com/universe/vapid/assets/65923862/0fb9acc5-27a3-4328-ad03-d3395606a1e2)

**More Context**
Bug submitted by Flavio Bravo - is hoping for a fix by next week as he has mailers going out that link to the website.

**Your Environment**
Include relevant details, so others can replicate the issue.
 - ios - most recent

**Comment by amiller-gh** [comment]
Fixed!
